# SPDX-License-Identifier: Apache-2.0

name: Build

on: [ push, pull_request ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "^1.15" ]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup
        run: make setup
      #- name: Lint
      #  run: make lint
      - name: Lint
        run: make check-headers
      - name: Test
        run: make test
      - name: Build
        run: make build
